# build only master branch on commit's
# all other branches build on PullRequest creation
branches:
  only:
    - master

language: rust

rust:
# build nightly only for the time beeing
  - nightly

matrix:
  fast_finish: false
  include:
    - name: "01_BLINKLED Aarch32"
      install:
        - sudo apt-get install gcc-aarch64-linux-gnu gcc-aarch64-linux-gnu
        - cargo install cargo-xbuild
        - rustup target add aarch64-unknown-linux-gnu
        - rustup component add rust-src
        - sudo chmod ugo+x ./01_BLINKLED/build.sh
        - cd ./01_BLINKLED
      script: ./build.sh 32 build travis

    - name: "01_BLINKLED Aarch64"
      install:
        - sudo apt-get install gcc-aarch64-linux-gnu gcc-aarch64-linux-gnu
        - cargo install cargo-xbuild
        - rustup target add aarch64-unknown-linux-gnu
        - rustup component add rust-src
        - sudo chmod ugo+x ./01_BLINKLED/build.sh
        - cd ./01_BLINKLED
      script: ./build.sh 64 build travis
